
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/students_info
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # use 'create', 'validate', 'none', or 'update' as needed
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  devtools:
    restart:
      enabled: true
